import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";
import Provider from "@/providers/QueryClient";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className + ' h-screen'}>
        <Provider>
            <Navbar />

            <main>
                <section className='container h-full pt-12'>
                    {children}
                </section>
            </main>

            <Footer />
        </Provider>
      </body>
    </html>
  )
}
